package Controllers;

import Models.Circulo;
import Models.Cuadrado;
import Models.Imagen;
import Models.Poligono;
import java.awt.Color;

/**
 *
 * @author Santi
 */
public class Interfaz extends javax.swing.JFrame {
    
    Lienzo miLienzo;
    Thread gameProcess;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.miLienzo = new Lienzo();
        this.miLienzo.setVisible(true);
        this.miLienzo.setSize(1000, 560);
        this.miLienzo.setBackground(Color.WHITE);
        this.add(this.miLienzo);
        
        Circulo s1 = new Circulo(4, Color.BLACK, Color.BLACK, 100, 100, 100);
        this.miLienzo.getMisFiguras().add(s1);
        
//        int x[] = {10,30,30,20,20,10};
//        int y[] = {10,10,30,30,20,20};
//        Cuadrado c1 = new Cuadrado(Color.BLACK, Color.blue, 10, 10, 50);
//        
//        Imagen i1 = new Imagen(150, 10, "src/Images/bmw.png", 50, 50);
//        Poligono p1 = new Poligono(Color.BLACK, Color.red, x, y);
//        
//        this.miLienzo.getMisFiguras().add(c1);
//        this.miLienzo.getMisFiguras().add(i1);
//        this.miLienzo.getMisFiguras().add(p1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bstart = new javax.swing.JButton();
        bstop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bstart.setText("Start");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });

        bstop.setText("Stop");
        bstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1040, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bstop)
                    .addComponent(bstart))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(bstart)
                .addGap(18, 18, 18)
                .addComponent(bstop)
                .addGap(189, 189, 189))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        if (!this.miLienzo.isPlaying()){
            this.gameProcess = new Thread(this.miLienzo);
            this.miLienzo.setPlaying(true);
            this.gameProcess.start();
        }
        
    }//GEN-LAST:event_bstartActionPerformed

    private void bstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstopActionPerformed
        this.miLienzo.setPlaying(false);
    }//GEN-LAST:event_bstopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstop;
    // End of variables declaration//GEN-END:variables
}
